### ISSUE TITLE
Folder has to be in a specific location to work

### ISSUE THREAD

**Issue by mint1246** [raga70/FullyAutomatedRedditVideoMakerBot#2]
All over the scripts theres stuff like: ~/RedditVideoMakerBot-master/venvDigger/bin/activate
That requires you to either change it to your actual directory, or move your folder there. 
I'm pretty sure there are better ways to get working directories, in python for example I saw with a quick search that you can do this:
dir_path = os.path.dirname(os.path.realpath(__file__))
I'm not a dev, but it would be a nice QOL change if you could implement it.

**Comment by raga70** [comment]
Modify the automathor.sh to reflect your path @jordanbr20  is working on a more flexible solution

**Comment by jordanbr20** [comment]
Yes, I am working on that Monday. Shouldn’t take long.
