### ISSUE TITLE
captionGen.py

### ISSUE THREAD

**Issue by simix** [raga70/FullyAutomatedRedditVideoMakerBot#4]
Hi, I love this project! How can I stop the title of a Reddit post from being captioned?
like this video:
https://www.tiktok.com/@reddit_owl/video/7323600886650047776

**Comment by jordanbr20** [comment]
Sorry, I am a bit behind because of college, this seems simple, I will see if I can fit it in shortly.

**Comment by jordanbr20** [comment]
Support added, see commit e6fc482.
